[api]
# The Base URL of your API Gateway
url = "https://r79hipbsdc.execute-api.us-east-1.amazonaws.com"

[auth]
# From your Terraform Output
user_pool_id = "us-east-1_DRsM3QUPw"
client_id = "5cqcsg20lv1i8nivk7im1am7q7"
region = "us-east-1"